const Color = Object.freeze({
  SCREEN_BACKGROUND: '#000000',
  RESULT_TEXT: '#FFFFFF',
  DIGIT_BACKGROUND: '#323232',
  DIGIT_TEXT: '#FFFFFF',
  COMPLEX_OPERATOR_TEXT: '#000000',
  COMPLEX_OPERATOR_BACKGROUND: '#A6A6A6',
  OPERATOR_TEXT: '#FFFFFF',
  OPERATOR_BACKGROUND: '#FD9326',
})

export default Color
